### USER
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "ridwansmpl36@gmail.com",
    "password": "elektron1928"
}

### 
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY2MDM2MjMsImV4cCI6MTczNjYwMzY4M30.6WkADL2Emh5PRHsMA9FjP8rq_3vElrkR1pCvd02zlLc

###
GET http://localhost:5000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY5MzY0NDMsImV4cCI6MTczNzAyMjg0M30.cD3Fb3IJZv_W0jc6Xd2vgfjDj0fbxk_DGhX4pZ6AXOg
Content-Type: application/json

{
    "email": "ridwansmpl36@gmail.com",
    "password": "elektron1928"
}

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "kontolodon",
    "email": "pantek@gmail.com",
    "password": "dahlah",
    "cpassword": "dahlah"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

### PRODUCT
POST http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA
Content-Type: application/json

{
  "name": "recomend 5",
  "image": "https://i.pinimg.com/736x/43/5d/a1/435da1b8e7e03d4b9d200180cbca6fe0.jpg",
  "price": "20000",
  "specs": "spek idol",
  "label": "rec",
  "stock": 100,
  "sold": 0,
  "rating": 4.5
}

###

GET http://localhost:5000/products/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA

###
PUT http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA
Content-Type: application/json

{
  "stock": 99,
  "sold": 1,
  "rating": 4.5
}
###
GET http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA

###
DELETE http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA

###
GET http://localhost:5000/products/New
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA
###
GET http://localhost:5000/products/second
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY3NzYxOTgsImV4cCI6MTczNjg2MjU5OH0.WEz9DDY50ev0XVcNblBOLdTAgNK2z7EYmgrw0nE-mBA

### CARTS
POST http://localhost:5000/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY4MTE4MDksImV4cCI6MTczNjg5ODIwOX0.NQdazK-aXrSr8eCebD81JitRVJ7a9p7jDVN94lhGAGI
Content-Type: application/json

{
  "productId": 14,
  "userId": 6,
  "quantity": 2
}
###
PUT http://localhost:5000/carts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY4MTE4MDksImV4cCI6MTczNjg5ODIwOX0.NQdazK-aXrSr8eCebD81JitRVJ7a9p7jDVN94lhGAGI
Content-Type: application/json

{

  "quantity": 3
}

###
GET http://localhost:5000/carts/user/7 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY4MTE4MDksImV4cCI6MTczNjg5ODIwOX0.NQdazK-aXrSr8eCebD81JitRVJ7a9p7jDVN94lhGAGI

### Login Admin
POST http://localhost:5000/admin/login
Content-Type: application/json

{
  "email": "admin123@gmail.com",
  "password": "admin123"
}

###
GET http://localhost:5000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoxLCJuYW1lIjoiTXVoYW1tYWQgUmlkd2FuIiwiZW1haWwiOiJhZG1pbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc0NzU5NTgsImV4cCI6MTczNzU2MjM1OH0.FQFh-a7-eNjkOX5YmBlr5gGSLk1NTkoBLMdPr5PZL9c

### Refresh Admin Token
GET http://localhost:5000/admin/token

###

### Get Admin Data (requires Authorization)
GET http://localhost:5000/admin/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoxLCJuYW1lIjoiTXVoYW1tYWQgUmlkd2FuIiwiZW1haWwiOiJhZG1pbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc0NzU5NTgsImV4cCI6MTczNzU2MjM1OH0.FQFh-a7-eNjkOX5YmBlr5gGSLk1NTkoBLMdPr5PZL9c
Content-Type: application/json

{
    "email": "admin123@gmail.com",
    "password": "admin123"
}
###

### Get Admin Orders (requires Authorization)
GET http://localhost:5000/admin/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoxLCJuYW1lIjoiTXVoYW1tYWQgUmlkd2FuIiwiZW1haWwiOiJhZG1pbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3MzcxNzIzNjcsImV4cCI6MTczNzI1ODc2N30.nkLWTHRYLTHcrWVUS0RBbZtSGwAVqW9xbHKrCVfosJg



### Update Order Status (requires Authorization)
PUT http://localhost:5000/admin/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoxLCJuYW1lIjoiTXVoYW1tYWQgUmlkd2FuIiwiZW1haWwiOiJhZG1pbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3MzcxNzIwNTgsImV4cCI6MTczNzI1ODQ1OH0.HgcydR9PCeANjQKvRS-Hzwafo-tOXUFLR1g83e8bxe0
Content-Type: application/json

{
  "stock": "2"
}

###
GET http://localhost:5000/admin/orders
### Logout Admin
DELETE http://localhost:5000/admin/logout