GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaWR3YW4iLCJlbWFpbCI6InJpZHdhbnNtcGwzNkBnbWFpbC5jb20iLCJpYXQiOjE3MzY2MDM2MjMsImV4cCI6MTczNjYwMzY4M30.6WkADL2Emh5PRHsMA9FjP8rq_3vElrkR1pCvd02zlLc

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "kontolodon",
    "email": "pantek@gmail.com",
    "password": "dahlah",
    "cpassword": "dahlah"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "ridwansmpl36@gmail.com",
    "password": "elektron1928"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout